services:
  db:
    container_name: parkmate_db
    image: postgres
    restart: always
    ports:
      - "2010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_parkmate:/var/lib/postgresql/data

volumes:
  db_data_parkmate:
   